package org.zixing.util.his.call;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6 2018-08-28T10:57:59.187+08:00
 * Generated source version: 3.2.6
 *
 */
public final class Test_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://common.ws.zxxy.com/", "WebServicePublishService");

	private Test_Client() {
	}

	public static void main(String args[]) throws Exception {
		
		
		URL wsdlURL = WebServicePublishService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}
 
		WebServicePublishService ss = new WebServicePublishService(wsdlURL,  
				SERVICE_NAME);
		WebServiceInterface port = ss.getWebServicePublishPort();

		{
			System.out.println("Invoking webservice...");
			//Ⱦɫ����
			String _webservice_arg0 = "";
			try {
				String _webservice__return = port
						.webservice(_webservice_arg0);
				System.out.println("webservice.result=" + _webservice__return);  

			} catch (WsException_Exception e) {
				System.out
						.println("Expected exception: WsException has occurred.");
				System.out.println(e.toString());
			}
		}

		System.exit(0);
	}
	


}
