package org.zixing.util.his.call;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-28T10:57:59.237+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://common.ws.zxxy.com/", name = "WebServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "webservice", targetNamespace = "http://common.ws.zxxy.com/", className = "org.zixing.util.his.call.Webservice")
    @ResponseWrapper(localName = "webserviceResponse", targetNamespace = "http://common.ws.zxxy.com/", className = "org.zixing.util.his.call.WebserviceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String webservice(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws WsException_Exception;
}
