
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.zixing.util.his.call;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-28T10:57:59.230+08:00
 * Generated source version: 3.2.6
 *
 */

@WebService(
                      serviceName = "WebServicePublishService",
                      portName = "WebServicePublishPort",
                      targetNamespace = "http://common.ws.zxxy.com/",
                      wsdlLocation = WsZxBaseInfo.wsdlLocation,
                      endpointInterface = "org.zixing.util.his.call.WebServiceInterface")

public class WebServicePublishPortImpl implements WebServiceInterface {

    private static final Logger LOG = Logger.getLogger(WebServicePublishPortImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.webservice.WebServiceInterface#webservice(java.lang.String arg0)*
     */
    public String webservice(String arg0) throws WsException_Exception {
        LOG.info("Executing operation webservice");
        System.out.println(arg0);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new WsException_Exception("WsException...");
    }

}
