
package org.zixing.util.his.call;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-28T10:57:59.225+08:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "WsException", targetNamespace = "http://common.ws.zxxy.com/")
public class WsException_Exception extends Exception {

    private org.zixing.util.his.call.WsException wsException;

    public WsException_Exception() {
        super();
    }

    public WsException_Exception(String message) {
        super(message);
    }

    public WsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WsException_Exception(String message, org.zixing.util.his.call.WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WsException_Exception(String message, org.zixing.util.his.call.WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public org.zixing.util.his.call.WsException getFaultInfo() {
        return this.wsException;
    }
}
