$(function(){
	//列表加载
	$("#li_analyse_show_a").click(function(){
		window.location.href='/chromosome/page/jsp/caryogram/operation/caryanalyse.jsp';
	});
	$("#li_count_a").click(function(){
		window.location.href='/chromosome/page/jsp/caryogram/operation/carycount.jsp';
	});
});
